### ISSUE TITLE
[HELP] Integration with Entra ID + Nginx Ingress

### ISSUE THREAD

**Issue by eabud** [tumbl3w33d/nexus-oauth2-proxy-plugin#32]
I successfully installed OAuth2-Proxy using a Helm chart, along with NGINX Ingress and Nexus, and all three components are running smoothly. I can also see the OAuth2ProxyRealm in Nexus. 

OAuth2-Proxy is configured with Microsoft Entra ID and he authentication process redirects to Microsoft Entra ID, and login functionality is working as expected.

I can also see in Chrome after every successful login through Microsoft Entra ID two cookies _oauth2_proxy_1 and _oauth2_proxy_0.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus3-ingress
  namespace: nexus
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;
        access_by_lua_block {
          if ngx.var.name_upstream_1 ~= "" then
            ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
          end
        }
spec:
  ingressClassName: nginx
  rules:
    - host: nexus.poc.com 
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nexus3-service  
                port:
                  number: 8081
  tls:
  - hosts:
    - nexus.poc.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4 128k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "128k"
spec:
  ingressClassName: nginx
  rules:
    - host: nexus.poc.com
      http:
        paths:
          - pathType: Prefix
            path: /oauth2
            backend:
              service:
                name: oauth2-proxy 
                port:
                  number: 80
```
When i am redirected to Nexus, nothing is happining. Am new to Nexus, am I missing something here ?

**Comment by tumbl3w33d** [comment]
Hi,

when nothing happens on Nexus side at all it makes me wonder whether you activated the realm that comes with the plugin (and moved it to the first position in the list). There is a screenshot in the README in the installation section.

There is also the troubleshooting section which explains how you can get exhaustive debug information (I can assist you with that if it's not clear enough). This would show you what headers have been received and if any processing of the plugin happened at all.

Besides, having 2 OAuth2 Proxy cookies indicates that a lot of information comes with the session, which is usually caused by the list of groups being transferred. That is pretty much to be expected and mentioned in the README as well. In that case the recommendation is to use OAuth2 Proxy's redis session storage. Not having that _could_ cause issues for you yet (but I don't think your current problem is caused by it). If that would be the cause, you usually get a status 431 from Nexus instead of nothing happening.

**Comment by eabud** [comment]
Thank you for your quick response.

Yes, I followed the instructions in the README file to activate it.  Could you please share the link to the troubleshooting section. I have a feeling that Nexus is not receiving the required headers.

**Comment by eabud** [comment]
Ok I found it. I activated and I can now understand what is happening: 

2025-02-06 08:23:49,705+0000 DEBUG [qtp1667994514-841] *UNKNOWN com.github.tumbl3w33d.OAuth2ProxyHeaderAuthTokenFactory - required OAuth2 proxy headers incomplete - X-Forwarded-User: null - X-Forwarded-Email: null - X-Forwarded-Preferred-Username: null

No headers are forwarded to nexus, as expected. I will share later more details and will share the end working solution here.

**Comment by eabud** [comment]
It seems like my issue is related to the integration between oauth2-proxy and ingress-nginx. The logs show a successful login, and I can see the authenticated user's username. However, the headers aren't being passed to Nexus. I'm using oauth2-proxy as a middleware in this setup.

`10.0.11.249:45272 - 0b39a6b5ca1015ab379fcedc64efda17 - elia****@gmail.com [2025/02/08 18:50:37] nexus.poc-***.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" 202 0 0.000`

do you offer a (paid) service to debug it or could you please help me to figure it out?

**Comment by eabud** [comment]
I updated the setup and decided to use OAuth2-Proxy as a reverse proxy instead of a middleware. The new flow is: **Load Balancer → Nginx → OAuth2-Proxy → Nexus**. 

```
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=entra-id
        - --email-domain=*
        - --upstream="http://nexus3-service.nexus.svc.cluster.local:8081"
        - --http-address=0.0.0.0:4180
        - --redirect-url=https://nexus.poc.com/oauth2/callback
        - --backend-logout-url=
        - --oidc-issuer-url=
        - --code-challenge-method=S256
        **- --reverse-proxy=true**
        - --cookie-secure=false
        - --set-xauthrequest=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: ""
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: ""
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: ""
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
```

and nginx ingress for nexus:

```
apiVersion: v1
kind: Namespace
metadata:
  name: nexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      securityContext:           
        runAsUser: 0  # Root user           
      containers:
        - name: nexus3
          image: sonatype/nexus3:latest
          ports:
            - containerPort: 8081
          env:
            - name: NEXUS_CONTEXT
              value: "/"
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
---
apiVersion: v1
kind: Service
metadata:
  name: nexus3-service
  namespace: nexus
spec:
  selector:
    app: nexus3
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus3-ingress
  namespace: oauth2-proxy
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "64k"
spec:      
  ingressClassName: nginx
  rules:
    - host: nexus.poc.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180
  tls:
  - hosts:
    - nexus.poc.com
```
