### ISSUE TITLE
[FEATURE] Make auth headers configurable

### ISSUE THREAD

**Issue by gryffus** [tumbl3w33d/nexus-oauth2-proxy-plugin#37]
I am using oauth2-proxy in forwardauth/auth_request mode, using traefik forwardauth middleware, which does not forward `X-Forwarded-*` headers, but uses `X-Auth-Request-*` set.

https://github.com/oauth2-proxy/oauth2-proxy/issues/1441#issuecomment-968384528

I came up with a simple solution, just make the header names configurable for nexus-oauth2-proxy-plugin, which would allow using it with broader set of oauth proxies out there.

For that, I wrote a simple patch, just grabbing those values from environment variables and setting them. It uses the default set when not present, so it should not affect current installs.

```
OAUTH2_PROXY_HEADER_USER (default: X-Forwarded-User)
OAUTH2_PROXY_HEADER_PREFERRED_USERNAME (default: X-Forwarded-Preferred-Username)
OAUTH2_PROXY_HEADER_EMAIL (default: X-Forwarded-Email)
OAUTH2_PROXY_HEADER_ACCESS_TOKEN (default: X-Forwarded-Access-Token)
OAUTH2_PROXY_HEADER_GROUPS (default: X-Forwarded-Groups)
```

Example settings (docker compose):

```
    environment:
      OAUTH2_PROXY_HEADER_USER: "X-Auth-Request-User"
      OAUTH2_PROXY_HEADER_PREFERRED_USERNAME: "X-Auth-Request-Preferred-Username"
      OAUTH2_PROXY_HEADER_EMAIL: "X-Auth-Request-Email"
      OAUTH2_PROXY_HEADER_ACCESS_TOKEN: "X-Auth-Request-Access-Token"
      OAUTH2_PROXY_HEADER_GROUPS: "X-Auth-Request-Groups"

```

https://github.com/tumbl3w33d/nexus-oauth2-proxy-plugin/pull/36
