### ISSUE TITLE
Installing plugin

### ISSUE THREAD

**Issue by jav-12** [tumbl3w33d/nexus-oauth2-proxy-plugin#8]
Sorry for creating a ticket for this silly question but, how I install this plugin in my Nexus oss implementation? I am using version 3.70

**Comment by Fredouye** [comment]
Hi

I've just started testing this plugin.

With Nexus 3.71 OSS (which can only handle H2 database) and Docker Compose, you can enable the 3.0 release of the plugin in `docker-compose.yml` : 

```yaml
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.71.0-java17-alpine
    volumes:
      - nexus_data:/nexus-data
      - ./nexus-oauth2-proxy-plugin-3.0.0-bundle.kar:/opt/sonatype/nexus/deploy/nexus-oauth2-proxy-plugin-3.0.0-bundle.kar
```
